<template>
    <div>
        
    </div>
</template>

<script>
import mm from '@/json/mm.json'
export default {
    mm: mm,
    data: () => ({
        label: {
            mm: {
                title: 'ကိုယ်ရေးအချက်အလက် ထည့်သွင်းရန်',
                name: 'အမည်',
                age: 'အသက်',
                dob: 'မွေးသက္ကရာဇ်',
                year: 'နှစ်',
                month: 'လ',
                day: 'ရက်',
                homeAddress: 'မွေးရပ်မြေ',
                currentAddress: 'လက်ရှိနေရပ်',
                gender: 'ကျား/မ',
                male: 'ကျား',
                female: 'မ',
                religion: 'ဘာသာ',
                nation: 'လူမျိုး',
                blood: 'သွေးအမျိုးအစား',
                dateOfDecision: 'ဂျပန်သွားရန် ဆုံးဖြတ်သည့်နေ့',
                noOfInterview: 'အင်တာဗျူးအကြိမ်အရေအတွက်',
                leftOrRight: 'ဘယ်သန်/ညာသန်',
                vision: 'အမြင်အား',
                glasses: 'မျက်မှန်ပါ',
                nanGlasses: 'မျက်မှန်မပါ',
                colorView: 'အရောင် အမြင်အာရုံ',
                bothEye: 'နှစ်ဘက်စလုံး',
                handPower: 'လက်ဆွဲအား',
                left: 'ဘယ်',
                right: 'ညာ',
                high:'အရပ်',
                weight: 'အလေးချိန်',
                tattoo: 'တက်တူး',
                yes: 'ရှိ',
                no: 'မရှိ',
                leftEye: 'ဘယ်မျက်လုံး',
                rightEye: 'ညာမျက်လုံး',
                smoke: 'ဆေးလိပ်',
                dink: 'သောက်',
                noDink: 'မသောက်',
                alcohol: 'အရက်',
                livingWithPeople: 'အများနှင့်နေထိုင်ခြင်း',
                married: 'အိမ်ထောင်',
                lover: 'ချစ်သူ/ရည်းစား',
                wedding: 'လက်ထပ်ရန်အစီအစဥ်',
                expense: 'ဂျပန်သွားရန်စရိတ်',
                self: 'ကိုယ်တိုင်',
                parants: 'မိဘ',
                relative: 'ဆွေမျိုး',
                bank: 'ဘဏ်',
                other: 'အခြား',
                threeYearIncome: '(၃) နှစ်စုဆောင်းချင်သော ငွေပမာဏ',
                kyats: 'ကျပ်',
                howToUse: '၀င်ငွေကို ဘာလုပ်မှာလဲ'
            },
            jp: {
                title: 'プロフィール',
                name: '名前',
                age: '年齢',
                dob: '生年月日',
                year: '年',
                month: '月',
                day: '日',
                homeAddress: '自宅住所',
                currentAddress: '現住所',
                gender: '男女',
                male: '男性',
                female: '女性',
                religion: '宗教',
                nation: '国家',
                blood: '血液',
                dateOfDecision: '日本に行く決定の日付',
                noOfInterview: 'インタビューの数',
                leftOrRight: '左利き/右利き',
                vision: 'ビジョン',
                glasses: 'メガネを着用',
                nanGlasses: 'メガネなし',
                colorView: '色覚',
                bothEye: '両側',
                handPower: '手の力',
                left: '左',
                right: '右',
                high:'高さ',
                weight: '重量',
                tattoo: '入れ墨',
                yes: 'ရှိ',
                no: 'မရှိ',
                leftEye: 'ဘယ်မျက်လုံး',
                rightEye: 'ညာမျက်လုံး',
                smoke: 'ဆေးလိပ်',
                dink: 'သောက်',
                noDink: 'မသောက်',
                alcohol: 'အရက်',
                livingWithPeople: 'အများနှင့်နေထိုင်ခြင်း',
                married: 'အိမ်ထောင်',
                lover: 'ချစ်သူ/ရည်းစား',
                wedding: 'လက်ထပ်ရန်အစီအစဥ်',
                expense: 'ဂျပန်သွားရန်စရိတ်',
                self: 'ကိုယ်တိုင်',
                parants: 'မိဘ',
                relative: 'ဆွေမျိုး',
                bank: 'ဘဏ်',
                other: 'အခြား',
                threeYearIncome: '(၃) နှစ်စုဆောင်းချင်သော ငွေပမာဏ',
                kyats: 'ကျပ်',
                howToUse: '၀င်ငွေကို ဘာလုပ်မှာလဲ'
            }
        }
    })
}
</script>